# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

#class TestTest():
#  def setup_method(self, method):
driver = webdriver.Chrome()
vars = {}
  
#  def teardown_method(self, method):
driver.quit()
  
#  def test_test(self):
driver.get("http://192.168.10.8:8083/index.php")
driver.set_window_size(1886, 1016)
driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
driver.find_element(By.NAME, "email").click()
driver.find_element(By.NAME, "email").send_keys("test@test.fr")
driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control-label").click()
elements = driver.find_elements(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control-label")
assert len(elements) > 0
driver.find_element(By.NAME, "password").click()
driver.find_element(By.NAME, "password").send_keys("Jfm2000m!")
driver.find_element(By.ID, "submit-login").click()
elements = find_elements(By.CSS_SELECTOR, ".logout")
assert len(elements) > 0
driver.find_element(By.CSS_SELECTOR, ".logout").click()
driver.close()
  
