<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxbmxcw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxbmxcw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxbmxcw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxbmxcw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxbmxcw\appProdProjectContainer([
    'container.build_hash' => 'Xxbmxcw',
    'container.build_id' => '9018ee6d',
    'container.build_time' => 1630403670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxbmxcw');
