FROM mariadb:10.3

ENV MYSQL_ROOT_PASSWORD=admin
ENV IPPRESTASHOP 172.18.0.2

COPY ./dump.sql /docker-entrypoint-initdb.d

EXPOSE 3306

COPY ./update.sql /docker-entrypoint-initdb.d

# docker build -t mariadbpresta .
# docker run -d --name mariadbpresta --rm mariadbpresta
# docker exec -ti mariadbpresta bash

# docker run -d --name mariadbpresta -e MYSQL_ROOT_PASSWORD=admin -p 3306:3306 --rm mariadbpresta
# docker exec -ti mariadbpresta bash


# Modification a faire dans SQL
# prestashop.ps_configuration champ PS_SHOP_DOMAIN, PS_SHOP_DOMAIN_SSL

# SELECT * FROM prestashop.ps_configuration
# where name in ('PS_SHOP_DOMAIN','PS_SHOP_DOMAIN_SSL');

# update prestashop.ps_configuration set value='172.18.0.2' where name in ('PS_SHOP_DOMAIN','PS_SHOP_DOMAIN_SSL');

# SELECT * FROM prestashop.ps_shop_url;

# update prestashop.ps_shop_url set domain = 'localhost:8083' where id_shop_url=1;
# update prestashop.ps_shop_url set domain_ssl = 'localhost:8083' where id_shop_url=1;
# update prestashop.ps_shop_url set physical_uri = '/' where id_shop_url=1;